default_stages:
  - pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key

  - repo: local
    hooks:
      # NOTE: This is a total unnecessary check, just used as part of the
      #       template. Remove this after creating the template.
      - id: check-python
        name: check-python
        entry: python --version
        language: system
        pass_filenames: no

      - id: ruff-linter
        name: ruff-linter
        entry: ruff check --fix
        language: system
        pass_filenames: true
        require_serial: yes
        files: "./"
        types:
          - python

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        pass_filenames: true
        require_serial: yes
        files: "./"
        types:
          - python

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        files: "src/sdx"
        pass_filenames: true
        types:
          - python

      - id: bandit
        name: bandit
        entry: bandit
        language: system
        args: ["--configfile", "pyproject.toml", "-iii", "-lll"]
        pass_filenames: true
        types:
          - python

      - id: vulture
        name: vulture
        entry: vulture
        language: system
        files: "src/sdx"
        description: Find unused Python code.
        pass_filenames: true
        types:
          - python
