---
title: ""
format:
  dashboard:
    logo: assets/images/thcai-logo.png
    nav-buttons:
      - icon: file
        title: report
        href: https://docs.google.com/document/d/15hE46jFvj5pnw4lbcJsg3NOOu0spqng-XktD4CuAUO4/edit?usp=sharing
    page-layout: custom
---
## Row

### Column {width=80%}

<h1>Report</h1>

This dashboard report is based on datasets obtained from the World Health Organization (WHO) and the National Bureau of Statistics (NBS), analyzing suicide cases from 2000 to 2019. It provides insights into the prevalence and patterns of suicide across different genders, with the aim of informing effective prevention strategies.

<h2>KEY FINDINGS</h2>

Insights derived from the analysis shows that the average suicide rate per was 4.32 percent with a population of 100,000 per year
Suicide Trends: There was a consistent and gradual decline in the suicide rate, dropping from 4.85 in 2000 to 3.49 in 2019. The highest rate was recorded in 2001 at 4.93, after which the trend generally moved downward, with more noticeable decreases occurring from 2010 onward. This steady reduction may reflect improvements in mental health awareness, access to support services, or broader socio-economic developments during the period.
Gender Disparity: Males accounted for 6.16% of total suicide cases, compared to 2.44% for females, highlighting a significant gender gap in suicide prevalence.

<h2>METHODOLOGY OVERVIEW</h2>

The datasets were analyzed using Python, Jupyter Notebook, Quarto, Quarto live, leveraging libraries such as Pandas, Matplotlib, Seaborn, and Plotly for data visualization. The analysis incorporated socioeconomic indicators—specifically poverty and unemployment rates—to explore their potential relationship with suicide trends.

<h2>INSIGHTS</h2>

The analysis revealed a concerning trend of higher suicide rates among males, with a significant correlation between socioeconomic factors and suicide incidence. Poverty and unemployment rates were strongly associated with increased suicide cases, emphasizing the need for targeted interventions that address these underlying issues. Additionally, the findings indicate that individuals aged 85 and above recorded the highest suicide rates, underscoring the importance of age-specific strategies for prevention and support.

<h2>RECOMMENDATIONS</h2>

The findings of this analysis have significant implications for policy and practice. The strong association between poverty, unemployment, and suicide rates highlights the need for a multifaceted approach to address these underlying issues. Recommendations include:
Improved access to mental health services and counselling
Economic empowerment programs and job creation initiatives to address unemployment

<h2>CONCLUSION</h2>

The insights from this analysis underscore the importance of addressing the root causes of suicide rather than merely its symptoms. Tackling poverty and unemployment, alongside ensuring access to comprehensive mental health support, is essential for fostering a safer and more supportive environment that promotes the well-being of all individuals.
