name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-branch:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 2
    concurrency:
      group: check-pr-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if the PR's branch is updated
        uses: osl-incubator/gh-check-pr-is-updated@1.0.0
        with:
          remote_branch: origin/main
          pr_sha: ${{ github.event.pull_request.head.sha }}

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ci-${{ github.event_name }}-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Conda Packages
        uses: actions/cache@v3
        with:
          path: ~/.conda/envs/suicide-nigeria
          key: ubuntu-latest-conda-${{ hashFiles('conda/dev.yaml') }}
          restore-keys: |
            ubuntu-latest-conda-

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: suicide-nigeria
          auto-update-conda: true
          conda-solver: libmamba

      - name: Run tests
        run: |
          makim tests.unit

      - name: Run style checks
        if: success() || failure()
        run: |
          pre-commit install
          makim tests.linter
